#!/usr/bin/env python

"""
Convert a unitcell in a GULP output file to a VASP-formatted file.

"""

import sys

from unitcell import UnitCell

with open(sys.argv[1], 'r') as cell_file:
    cell = UnitCell(cell_file,"gulp_output")
vasp = cell.output_vasp()
print vasp
