#!/usr/bin/env python

"""
Script to extract unitcell information from a GULP output file and reformat it
as a GULP input file.

"""

import sys

from unitcell import UnitCell

with open(sys.argv[1], 'r') as cell_file:
    cell = UnitCell(cell_file, "gulp_output")
gulp = cell.output_gulp()
print gulp
