#!/software/enthought/python/epd-7.3-2-rh5-x86_64/bin/python
from unitcell import *
import sys

file = sys.argv[1]
cell_file = open(file,'r')
cell = UnitCell(cell_file)
findsym = cell.output_findsym()
print findsym
