#!/usr/bin/env python

"""
Convert a VASP-formatted file to a findsym-formatted file.

"""

import sys

from unitcell import UnitCell

with open(sys.argv[1], 'r') as cell_file:
    cell = UnitCell(cell_file)
findsym = cell.output_findsym()
print findsym
