#!/usr/bin/env python

"""
Convert VASP-formatted unitcell to a LAMMPS-formatted file.
Only supports orthogonal cells with cell vector directions pointing along x, y,
and z, respectively.

"""

import sys

from unitcell import UnitCell
with open(sys.argv[1], 'r') as poscar:
    unit_cell = UnitCell(poscar)
text = unit_cell.output_lammps()
print text
