#!/usr/bin/env python

"""
Script to convert VASP-formatted unitcell to a GULP-formatted unitcell.

"""

import sys

from unitcell import UnitCell

with open(sys.argv[1], 'r') as cell_file:
    cell = UnitCell(cell_file)
gulp = cell.output_gulp()
print gulp
